name: etqan_edu_app
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.1+21

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^6.3.3
  better_player_plus: ^1.0.8
  cached_network_image_plus: ^0.0.5
  chewie: ^1.11.3
  onesignal_flutter: ^5.3.4
  connectivity_plus: ^6.1.1
  country_flags: ^3.2.0
  country_picker: ^2.0.27
  # cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  # device_preview: ^1.2.0
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  file_picker: ^8.1.7
  firebase_analytics: ^11.6.0
  firebase_core: ^3.13.0
  # firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_credit_card: ^4.0.0
  # flutter_inappwebview: ^6.1.5
  # flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.4
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  flutter_widget_from_html: ^0.15.3
  fpdart: ^1.1.1
  gap: ^3.0.1
  # geocoding: ^3.0.0
  # geolocator: ^14.0.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  # hive: ^4.0.0-dev.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.3
  intl: 0.20.2
  # intl: ^0.19.0
  # isar_flutter_libs: ^4.0.0-dev.14
  logger: null
  lottie: ^3.3.1
  # media_kit: ^1.1.11
  # media_kit_libs_video: ^1.0.5
  # media_kit_libs_windows_video: ^1.0.4
  # media_kit_video: ^1.2.5
  no_screenshot:
    path: no_screenshot-0.3.2-beta.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  # percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  persian_number_utility: ^1.1.4
  # photo_view: ^0.15.0
  pinput: ^5.0.0
  retry: ^3.1.2
  screen_protector: ^1.4.2+1
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^29.1.41
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  # video_player_win: ^3.1.1
  wakelock_plus: ^1.3.2
  webview_flutter: ^4.10.0
  # webview_windows: ^0.4.0
  window_manager: ^0.3.7
  # window_size:
  #   git:
  #     url: https://github.com/YazanFarrah/flutter-control-desktop-size.git
  #     path: plugins/window_size
  package_info_plus: ^8.3.1
  firebase_crashlytics: ^4.3.10
  flutter_udid: ^4.0.0
  comment_tree: ^0.3.0
  liquid_glass_renderer: ^0.1.1-dev.10
  loading_animation_widget: ^1.3.0





dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


dependency_overrides:
#  sqflite_android: 2.4.1

# flutter_native_splash:
#   android: true
#   ios: true
#   web: false
#   color: "#6949FF"
#   color_dark: "#6949FF"
#   android_12:
#     color: "#6949FF"
#     color_dark: "#6949FF"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logot.png
    - assets/images/slogan.png
    - assets/icons/
    - assets/flags/
    - assets/svgs/
    - assets/svgs/bottom_navbar/
    - assets/animations/
    - assets/translations/en.json
    - assets/translations/ar.json
    - assets/json/countries.json
    - shorebird.yaml
