// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkwtoCHSIqqpgBZ7pl2J22r-nbI5t5cs',
    appId: '1:339385233809:android:361a488c389b48975caa30',
    messagingSenderId: '339385233809',
    projectId: 'etqan-fd4d3',
    storageBucket: 'etqan-fd4d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dZFeL9onTa50JzSw1DYsp40OaBKnWrU',
    appId: '1:339385233809:ios:57ea1d8beccd5a895caa30',
    messagingSenderId: '339385233809',
    projectId: 'etqan-fd4d3',
    storageBucket: 'etqan-fd4d3.firebasestorage.app',
    iosBundleId: 'com.tedreeb4edu.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczYqgAD12gvasmNn1Q_3-8F15MckBI4s',
    appId: '1:339385233809:web:45201367ce86362f5caa30',
    messagingSenderId: '339385233809',
    projectId: 'etqan-fd4d3',
    authDomain: 'etqan-fd4d3.firebaseapp.com',
    storageBucket: 'etqan-fd4d3.firebasestorage.app',
    measurementId: 'G-GNBD96JEK4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dZFeL9onTa50JzSw1DYsp40OaBKnWrU',
    appId: '1:339385233809:ios:5b276a3071de9ff25caa30',
    messagingSenderId: '339385233809',
    projectId: 'etqan-fd4d3',
    storageBucket: 'etqan-fd4d3.firebasestorage.app',
    iosBundleId: 'com.asas4edu.net.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBczYqgAD12gvasmNn1Q_3-8F15MckBI4s',
    appId: '1:339385233809:web:0100b780075bff8f5caa30',
    messagingSenderId: '339385233809',
    projectId: 'etqan-fd4d3',
    authDomain: 'etqan-fd4d3.firebaseapp.com',
    storageBucket: 'etqan-fd4d3.firebasestorage.app',
    measurementId: 'G-PQ5F3GY9SM',
  );

}